In [1]:
# Standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## 1.Getting our Data ready to be used with machine learning 
The main things we have to do:
    1. Split the data into features and labels(usaually 'x' and 'y')
    2. Filling (also called imputing) or disregarding missing values
    3. Converting non-numerical values to numerical values ( also called feature encoding )
    

In [2]:
heart_disease=pd.read_csv(r"heart-disease.csv")

In [3]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
x=heart_disease.drop("target",axis=1)

In [5]:
y=heart_disease["target"]

In [6]:
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [7]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [9]:
# Splitting the data into training data and test data 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2)

In [12]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

### 1.1 Getting Your Data Ready: Convert Data to number

* Make sure it's all numerical

In [14]:
car_sales=pd.read_csv(r"car-sales-extended.csv")

In [15]:
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [16]:
len(car_sales)

1000

In [17]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [18]:
# Split into X/y
X=car_sales.drop("Price",axis=1)
y=car_sales["Price"]

In [20]:
X.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [21]:
y.head()

0    15323
1    19943
2    28343
3    13434
4    14043
Name: Price, dtype: int64

In [22]:
# Split data into training data and test Data

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [33]:
# Build machine learning model
from sklearn.ensemble import RandomForestRegressor

model=RandomForestRegressor()
model.fit(X_train,y_train)
model.score(X_test,y_test)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


ValueError: could not convert string to float: 'Toyota'

In [34]:
# As you can see we need to turn features which have string datatypes to numbers 

In [36]:
# Turn Categories into number
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]

one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],remainder="passthrough")
transformed_x=transformer.fit_transform(X)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [37]:
pd.DataFrame(transformed_x)  # All string values converted to numerical values

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
5    0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   42652.0
6    0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  163453.0
7    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   43120.0
8    0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  130538.0
9    0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   51029.0
10   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  167421.0
11   0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0   17119.0
12   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  102303.0
13   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  134181.0
14   0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  199833.0
15   0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  205592.0
16   0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   96742.0
17   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  194189.0
18   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0   67991.0
19   0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  215820.0
20   0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  124844.0
21   0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   30615.0
22   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  148744.0
23   0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  130075.0
24   0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  172718.0
25   0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  125819.0
26   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  180390.0
27   0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0   82783.0
28   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   56687.0
29   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  112004.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
970  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  186309.0
971  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  178164.0
972  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  137690.0
973  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  237627.0
974  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  155383.0
975  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   22409.0
976  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   95317.0
977  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  128016.0
978  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0   85739.0
979  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   17975.0
980  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  230314.0
981  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  129454.0
982  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  238172.0
983  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  183330.0
984  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  157235.0
985  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  216250.0
986  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   71934.0
987  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215235.0
988  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  248736.0
989  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   41735.0
990  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  173408.0
991  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  235985.0
992  0.0  

In [41]:
# Another way of converting data using pandas
dummies=pd.get_dummies(car_sales[["Make","Colour","Doors"]]) # Here we have given a list of features who's datatype we want to convert
dummies.head(10)

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0      4         0           1            0            0             0   
1      5         1           0            0            0             0   
2      4         0           1            0            0             0   
3      4         0           0            0            1             0   
4      3         0           0            1            0             0   
5      4         0           1            0            0             0   
6      4         0           0            0            1             0   
7      4         0           1            0            0             0   
8      4         0           0            1            0             0   
9      4         0           1            0            0             0   

   Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0            0             0           0             1  
1            1             0           0             0  
2            0             0           0             1  
3            0             0           0             1  
4            1             0           0             0  
5            0             0           1             0  
6            1             0           0             0  
7            0             0           0             1  
8            0             0           0             1  
9            1             0           0             0

In [39]:
# Now Let's refit the model
np.random.seed(42)
X_train,X_test,y_train,y_test=train_test_split(transformed_x,y,test_size=0.2)
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.30431565439836705

### 1.2 Getting Your Data Ready: Handling missing data with pandas

1.2 What if there were missing values?
  1. Fill them with some value(also known as imputation)
  2. Remove the samples with missing data altogether

In [5]:
# Import car sales missing data 
car_sales_missing = pd.read_csv(r"C:\Users\DELL\Desktop\zero-to-mastery-ml\data\car-sales-extended-missing-data.csv")
car_sales_missing.head()


Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [6]:
# To find how many missing values do we have in data columns
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [7]:
# Now let's create X and y
X=car_sales_missing.drop("Price",axis=1)
y=car_sales_missing["Price"]

In [8]:
# Let's try to convert our data to numbers 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],remainder="passthrough")
transformed_x=transformer.fit_transform(X)
transformed_x

ValueError: Input contains NaN

In [9]:
# As you can see the data has missing values or data

#### Option 1. Filling missing data with pandas

In [10]:
# Fill the "make" column
car_sales_missing["Make"].fillna("missing",inplace=True)

# Fill the colour column
car_sales_missing["Colour"].fillna("missing", inplace=True)

# Fill the "Odometer (KM)" column
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(), inplace=True)

# Fill the "Doors"  column
car_sales_missing["Doors"].fillna(4, inplace=True)

car_sales_missing.isna().sum()


Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [11]:
# Remove rows with missing Price Value

In [12]:
car_sales_missing.dropna(inplace=True)
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [13]:
# Now let's create X and y
X=car_sales_missing.drop("Price",axis=1)
y=car_sales_missing["Price"]

In [15]:
# Let's try to convert our data to numbers 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],remainder="passthrough")
transformed_x=transformer.fit_transform(car_sales_missing)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

### Option 2. Filling missing values with scikit-learn 

In [2]:
car_sales_missing=pd.read_csv(r"C:\Users\DELL\Desktop\zero-to-mastery-ml\data\car-sales-extended-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [3]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [5]:
car_sales_missing.dropna(subset=["Price"],inplace=True)

In [6]:
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [7]:
# Split the data into X and y
from sklearn.model_selection import train_test_split

X=car_sales_missing.drop("Price",axis=1)
y=car_sales_missing["Price"]

np.random.seed(42)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [8]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [10]:
# Fill categorical values with missing and numberical values with means
car_impute=SimpleImputer(strategy="constant",fill_value="missing")
doors_impute=SimpleImputer(strategy="constant",fill_value=4)
Odometer_impute=SimpleImputer(strategy="mean")


In [12]:
# Define different column features
categorical_features=["Make","Colour"]
doors_feature=["Doors"]
numerical_features=["Odometer (KM)"]

In [14]:
imputer=ColumnTransformer([
                         ("car_imputer",car_impute,categorical_features),
                         ("doors_imputer",doors_impute,doors_feature),
                         ("Odometer_imputer",Odometer_impute,numerical_features)])

# Fill train and test values separately
filled_X_train=imputer.fit_transform(X_train)
filled_X_test=imputer.transform(X_test)

filled_X_train

array([['Honda', 'White', 4.0, 71934.0],
       ['Toyota', 'Red', 4.0, 162665.0],
       ['Honda', 'White', 4.0, 42844.0],
       ...,
       ['Toyota', 'White', 4.0, 196225.0],
       ['Honda', 'Blue', 4.0, 133117.0],
       ['Honda', 'missing', 4.0, 150582.0]], dtype=object)

In [15]:
# Get our transformed data array's back into DataFrame's
car_sales_missing_train=pd.DataFrame(filled_X_train,columns=["Make","Colour","Doors","Odometer (KM)"])

car_sales_missing_test=pd.DataFrame(filled_X_test,columns=["Make","Colour","Doors","Odometer (KM)"])

car_sales_missing_train.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [16]:
# Now check the original data for missing values
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [18]:
# Now let's convert categorical values of our data to numerical values
from sklearn.preprocessing import OneHotEncoder

categorical_features=["Make","Colour","Doors"]

one_hot=OneHotEncoder()

transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],remainder="passthrough")

transformed_X_train=transformer.fit_transform(car_sales_missing_train)

transformed_X_test=transformer.transform(car_sales_missing_test)

transformed_X_train.toarray()


array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 7.19340e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.62665e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 4.28440e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.96225e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.33117e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.50582e+05]])

In [22]:
# Now that we have transformed our data, let's see if we can fit a model 
np.random.seed(42)

from sklearn.ensemble import RandomForestRegressor

model=RandomForestRegressor(n_estimators=90)

model.fit(transformed_X_train,y_train)
model.score(transformed_X_test,y_test)

0.2149808210604971

## 2. Choosing the right estimator/algorithm for our problem

Scikit learn uses estimator as another term for machine learning model or algorithm
* Classification- predicting whether a sample is one thing or another
* Regression- predicting a number
* Step 1- Check the scikit learn machine learning map...https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

### 2.1 Picking a machine learning model for a regression problem

In [24]:
# Import Boston Housing dataset

In [28]:
from sklearn.datasets import load_boston
boston=load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [29]:
# Change this dataset to dataframe
boston_df=pd.DataFrame(boston["data"],columns=boston["feature_names"])
boston_df["target"]=pd.Series(boston["target"])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [30]:
# Following scikit learn machine learning map
# Let's try Ridge Regression model
from sklearn.linear_model import Ridge
# set up randon seed
np.random.seed(42)

# Create the data
X=boston_df.drop("target", axis=1)
y=boston_df["target"]

# split the data into train and test sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# Instantiate Ridge Model
model=Ridge()

model.fit(X_train,y_train)

# Check the score of ridge model on test data
model.score(X_test,y_test)




0.6662221670168522

In [31]:
# Still score of this model is quite low
# Let's see what we can do, refer back to machine leaning map...https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html
# According to the map if Ridge won't work then we can use Ensemble Regressors 
# So let's try RandomForestRegressor

In [35]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

x=boston_df.drop("target",axis=1)
Y=boston_df["target"]

x_train,x_test,Y_train,Y_test=train_test_split(x,Y,test_size=0.2)

rf=RandomForestRegressor(n_estimators=100)

rf.fit(x_train,Y_train)
rf.score(x_test,Y_test)

0.873969014117403

In [36]:
 # So as you can see our current machine learning is better than the previous one

## 2.2 Choosing an estimator for a classification problem

let's go the map....https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [52]:
heart_disease=pd.read_csv(r"C:\Users\DELL\Desktop\Machine-learning-and-data-science\Scikit-Learn\heart-disease.csv")

In [53]:
heart_disease.head(15)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0    63    1   3       145   233    1        0      150      0      2.3   
1    37    1   2       130   250    0        1      187      0      3.5   
2    41    0   1       130   204    0        0      172      0      1.4   
3    56    1   1       120   236    0        1      178      0      0.8   
4    57    0   0       120   354    0        1      163      1      0.6   
5    57    1   0       140   192    0        1      148      0      0.4   
6    56    0   1       140   294    0        0      153      0      1.3   
7    44    1   1       120   263    0        1      173      0      0.0   
8    52    1   2       172   199    1        1      162      0      0.5   
9    57    1   2       150   168    0        1      174      0      1.6   
10   54    1   0       140   239    0        1      160      0      1.2   
11   48    0   2       130   275    0        1      139      0      0.2   
12   49    1   1       130   266    0        1      171      0      0.6   
13   64    1   3       110   211    0        0      144      1      1.8   
14   58    0   3       150   283    1        0      162      0      1.0   

    slope  ca  thal  target  
0       0   0     1       1  
1       0   0     2       1  
2       2   0     2       1  
3       2   0     2       1  
4       2   0     2       1  
5       1   0     1       1  
6       1   0     2       1  
7       2   0     3       1  
8       2   0     3       1  
9       2   0     2       1  
10      2   0     2       1  
11      2   0     2       1  
12      2   0     2       1  
13      1   0     2       1  
14      2   0     2       1

So let's follow scikit-learn machine learning map to find the best machine learning maodel.....https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [39]:
# Checked the map and it says  LinearSCV

In [54]:
# Import LinearSCV estimator class
from sklearn.svm import LinearSVC

# Setup random seed 
np.random.seed(42)

# Define data 
X=heart_disease.drop("target",axis=1)
y=heart_disease["target"]

# Split train and test data sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# Define model
clf=LinearSVC()

# Fit model to the data 
clf.fit(X_train,y_train)

# Check score of the model
clf.score(X_test,y_test)



C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.4918032786885246

In [41]:
# So the model score showing, this model is not good enough 
# If the current model is not working, try different model 

Titbit:-
    1. If you have structured data, use ensemble methods
    2. If you have unstructured data, use deep learning or transfer learning

In [55]:
# So let's try ensemble class machine learning model
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Define data 
X=heart_disease.drop("target", axis=1)
y=heart_disease["target"]

# Split the data into test and train sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# Instantiate Model
model=RandomForestClassifier(n_estimators=100)

# Fit the model to the data
model.fit(X_train,y_train)

#  Let's check the score of our model on test data set
model.score(X_test,y_test)

0.8524590163934426

## 3. Fit the model/algorithm on our data and use it to make predictions

3.1 Fitting the model to the data 
 * X= features, feature variables,data
 * y= lables, targets, target variables

In [ ]:
# So let's try ensemble class machine learning model
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Define data 
X=heart_disease.drop("target", axis=1)
y=heart_disease["target"]

# Split the data into test and train sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# Instantiate Model
model=RandomForestClassifier(n_estimators=100)

# Fit the model to the data ( train the machine learning model with the training data set )
model.fit(X_train,y_train)

#  Let's check the score of our model on test data set (test the patterns learn by our model on the training data set by using test data set)
model.score(X_test,y_test)

### 3.2 Make predictions using machine learning model

2 Ways to make predictions:-
    1.`predict()`
    2.`predict_proba()`

In [47]:
# Use a trained model to make predictions
model.predict(1,2,3,4,5) # This doesn't work

TypeError: predict() takes 2 positional arguments but 6 were given

In [48]:
model.predict(X_test)  # Our model has made prediction on our given test data

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [49]:
np.array(y_test)   # Our original outcomes or true outcomes

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [50]:
# Compare predictions to the truth labels to evaluate the model
preds_y=model.predict(X_test)
np.mean(preds_y==y_test)

0.8524590163934426

In [56]:
# another way
from sklearn.metrics import accuracy_score
accuracy_score(y_test,preds_y)

0.8524590163934426

make predictions with `predict_proba()`


In [57]:
# predict_proba() returns probabilities of a classification label

In [59]:
model.predict_proba(X_test[:10])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82],
       [0.14, 0.86],
       [0.36, 0.64],
       [0.95, 0.05],
       [0.99, 0.01],
       [0.47, 0.53]])

In [60]:
model.predict(X_test[:10])

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1], dtype=int64)

In [ ]:
# As you can see predict_proba() predicts probabilities of 0s and 1s