In [170]:
import numpy as np
import pandas as pd

## Datatypes and Attributes

In [15]:
# NumPy's main datatype is ndarray

In [16]:
a1=np.array([1,2,3.3])
a1

array([1. , 2. , 3.3])

In [17]:
a2=np.array([[1,3,4.3],
             [2,5,6]])
a2

array([[1. , 3. , 4.3],
       [2. , 5. , 6. ]])

In [18]:
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
a4=np.array([[[1,2,3],
             [4,5,6]],
             [[7,8,9],
             [10,11,12]],
             [[13,14,15],
             [16,17,18]]])
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [20]:
a1.shape  # Shape of our array

(3,)

In [21]:
a2.shape

(2, 3)

In [22]:
a3.shape

(2, 3, 3)

In [23]:
a4.shape

(3, 2, 3)

In [24]:
a1.ndim, a2.ndim, a3.ndim, a4.ndim

(1, 2, 3, 3)

In [25]:
a1.dtype

dtype('float64')

In [26]:
a1.size,a2.size,a3.size, a4.size

(3, 6, 18, 18)

In [27]:
type(a1)

numpy.ndarray

In [28]:
# Create a dataframe from NumPy array

In [29]:
import pandas as pd

In [31]:
my_df=pd.DataFrame(a2)
my_df

0    1    2
0  1.0  3.0  4.3
1  2.0  5.0  6.0

## Creating NumPy arrays

In [34]:
sample_array=np.array([1,2,3])

In [35]:
sample_array

array([1, 2, 3])

In [37]:
ones=np.ones((2,3))   # Give back array filled with 1s
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
zeros=np.zeros((3,2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [41]:
range_array=np.arange(0,10,1)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
random_array=np.random.randint(0,10,size=(3,3))
random_array

array([[4, 9, 8],
       [7, 0, 2],
       [8, 1, 2]])

In [46]:
random_array2=np.random.random((4,5))
random_array2

array([[0.26605175, 0.70610404, 0.27152091, 0.97664857, 0.59136674],
       [0.86321441, 0.81931077, 0.34199711, 0.9180317 , 0.31640466],
       [0.61979309, 0.4972481 , 0.6816239 , 0.3086655 , 0.48811737],
       [0.86350893, 0.28989147, 0.01835791, 0.46342781, 0.30675891]])

In [48]:
random_array3=np.random.rand(4,5)
random_array3

array([[0.49688737, 0.16588122, 0.64118697, 0.76266416, 0.74189363],
       [0.69871052, 0.41919297, 0.89006473, 0.73416474, 0.62214483],
       [0.81889144, 0.66745501, 0.12131806, 0.40549358, 0.33301724],
       [0.94669681, 0.53148518, 0.75434649, 0.34115211, 0.81254307]])

## Psuedo Random Numbers

In [49]:
# WE will np.random.seed() to see how psuedo random numbers works

In [60]:
psuedo_random=np.random.randint(10,size=(3,4))
psuedo_random

array([[6, 2, 6, 0],
       [2, 4, 0, 7],
       [8, 3, 6, 1]])

In [62]:
# Our Psuedo random will keep changing everytime we run our cell. But by using np.random.seed() we can get a unique random array

In [65]:
np.random.seed(seed=4)   # now our array will not change no matter how many time you run the cell
psuedo_random

array([[6, 2, 6, 0],
       [2, 4, 0, 7],
       [8, 3, 6, 1]])

## Viewing arrays and Matrices:

In [66]:
# To get unique elements of our array we use unique method

In [67]:
np.unique(psuedo_random)  # Give back unique elements present in our array

array([0, 1, 2, 3, 4, 6, 7, 8])

In [68]:
a2

array([[1. , 3. , 4.3],
       [2. , 5. , 6. ]])

In [69]:
a2[0]

array([1. , 3. , 4.3])

In [71]:
a2[0][1]

3.0

In [72]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [90]:
a3[:2,:2,:3]  # [:axis0,:row,:column]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [91]:
a3[0][0][:3]

array([1, 2, 3])

In [92]:
a6=np.random.randint(10,size=(2,3,4,5))
a6

array([[[[7, 5, 1, 8, 7],
         [8, 2, 9, 7, 7],
         [7, 9, 8, 4, 2],
         [6, 4, 3, 0, 7]],

        [[5, 5, 9, 6, 6],
         [8, 2, 5, 8, 1],
         [2, 7, 0, 8, 3],
         [1, 0, 3, 2, 3]],

        [[2, 9, 2, 1, 0],
         [1, 9, 9, 0, 7],
         [2, 6, 3, 7, 8],
         [2, 6, 7, 7, 9]]],


       [[[2, 7, 5, 3, 0],
         [5, 4, 3, 8, 9],
         [5, 8, 6, 7, 0],
         [4, 6, 8, 4, 8]],

        [[1, 9, 5, 4, 2],
         [3, 4, 7, 6, 6],
         [8, 0, 3, 5, 6],
         [1, 1, 6, 0, 8]],

        [[7, 5, 7, 6, 8],
         [4, 4, 0, 7, 2],
         [1, 8, 8, 1, 3],
         [1, 3, 6, 7, 4]]]])

In [99]:
a6[:,:,:,:2]

array([[[[7, 5],
         [8, 2],
         [7, 9],
         [6, 4]],

        [[5, 5],
         [8, 2],
         [2, 7],
         [1, 0]],

        [[2, 9],
         [1, 9],
         [2, 6],
         [2, 6]]],


       [[[2, 7],
         [5, 4],
         [5, 8],
         [4, 6]],

        [[1, 9],
         [3, 4],
         [8, 0],
         [1, 1]],

        [[7, 5],
         [4, 4],
         [1, 8],
         [1, 3]]]])

## Manipulating and Comparing Arrays

In [1]:
# Arithmetic

In [102]:
a1

array([1. , 2. , 3.3])

In [103]:
a2

array([[1. , 3. , 4.3],
       [2. , 5. , 6. ]])

In [105]:
a_1=np.ones(3)
a_1

array([1., 1., 1.])

In [108]:
a1+a_1

array([2. , 3. , 4.3])

In [107]:
a1 + a2  # Adding a1 elements in both rows of a2

array([[2. , 5. , 7.6],
       [3. , 7. , 9.3]])

In [109]:
a1*a_1

array([1. , 2. , 3.3])

In [110]:
a1*a2

array([[ 1.  ,  6.  , 14.19],
       [ 2.  , 10.  , 19.8 ]])

In [111]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [112]:
a2+a3   # We can't multiply array a2 to array a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [116]:
np.log(a1)   # To find log value of elements of  array a1 

array([0.        , 0.69314718, 1.19392247])

In [114]:
np.log(a2)

array([[0.        , 1.09861229, 1.45861502],
       [0.69314718, 1.60943791, 1.79175947]])

In [115]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 27.11263892])

## Aggregation
Aggregation = performing the same operation on a number of things

In [117]:
a_2=np.array([1,2,3])

In [118]:
sum(a_2)

6

In [119]:
np.sum(a_2)

6

In [120]:
# We can perform same sum method using python and NumPy but the main difference is that NumPy can perform operation much faster

In [122]:
# Example let's understand this concept using massive array

In [123]:
massive_array=np.random.random((100000))

In [124]:
# We will magic module of python timeit to see time taken by both sum() and np.sum()

In [125]:
%timeit sum(massive_array)

37.5 ms ± 4.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [126]:
%timeit np.sum(massive_array)

90.8 µs ± 4.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [127]:
# As you can see there is a huge difference between their executing time

In [128]:
a2

array([[1. , 3. , 4.3],
       [2. , 5. , 6. ]])

In [129]:
np.mean(a2)

3.5500000000000003

In [130]:
np.max(a2)

6.0

In [131]:
np.min(a2)

1.0

In [134]:
np.std(a2)  # Standard deviation and variance

1.7260262647673315

In [133]:
np.var(a2)

2.9791666666666665

Standard deviation is a statisic that looks at how far from the mean of a group of number is using square root of the variance.
The calculation of variance uses squares.

Variance is the average of the squared differences from the mean. To figure out the variance, first calulate the difference
between each point and the mean then, square and average the results

In [135]:
np.sqrt(np.var(a2))

1.7260262647673315

In [136]:
high_var_array=np.array([1,100,200,300,4000,5000])
low_var_array=np.array([2,4,6,8,10])

In [137]:
np.var(high_var_array),np.var(low_var_array)

(4296133.472222221, 8.0)

## Reshape and Transposing

In [138]:
a2

array([[1. , 3. , 4.3],
       [2. , 5. , 6. ]])

In [140]:
a2.shape

(2, 3)

In [145]:
a2.reshape(2,3,1)

array([[[1. ],
        [3. ],
        [4.3]],

       [[2. ],
        [5. ],
        [6. ]]])

In [146]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [148]:
a3*a2.reshape(2,3,1)

array([[[  1. ,   2. ,   3. ],
        [ 12. ,  15. ,  18. ],
        [ 30.1,  34.4,  38.7]],

       [[ 20. ,  22. ,  24. ],
        [ 65. ,  70. ,  75. ],
        [ 96. , 102. , 108. ]]])

In [149]:
# Transpose

In [152]:
a2.T    # it will transpose our matrix or array

array([[1. , 2. ],
       [3. , 5. ],
       [4.3, 6. ]])

## Dot Product vs Element Wise

In [154]:
np.random.seed(0)
mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))

In [155]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [156]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [157]:
# Element Wise Multiplication

In [158]:
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [159]:
# Dot product

In [160]:
mat3=np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [161]:
# Right now we cannot perform dot product of mat1 and mat2 because of their shape right now their shape is (5,3) and (5,3)
# respectively to get their dot product we have to match the inner dimension of these two arrays like (5,3) and (3,5)

In [164]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [166]:
mat2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [163]:
mat3=np.dot(mat1,mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Dot Product Example

In [167]:
# Nut Butter jar sales

In [168]:
np.random.seed(0)
# Number of jars sold
sales_amount=np.random.randint(10,size=(5,3))
sales_amount

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [169]:
# Using pandas for creating a weekly_sales data frame

In [171]:
weekly_sales=pd.DataFrame(sales_amount,index=["Mon","Tues","Wed","Thurs","Fri"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])

In [172]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon                5              0              3
Tues               3              7              9
Wed                3              5              2
Thurs              4              7              6
Fri                8              8              1

In [173]:
# Now create prices array

In [174]:
prices=np.array([10,8,12])

In [175]:
butter_prices=pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])

In [176]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [180]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [181]:
daily_sales=butter_prices.dot(weekly_sales.T)

In [182]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price   86   194   94    168  156

In [184]:
weekly_sales["Total (Rs)"]=daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total (Rs)
Mon                5              0              3          86
Tues               3              7              9         194
Wed                3              5              2          94
Thurs              4              7              6         168
Fri                8              8              1         156

## Sorting Arrays

In [185]:
random_array=np.random.randint(10,size=(3,5))

In [186]:
random_array

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]])

In [187]:
# np.sort()


In [188]:
np.sort(random_array)

array([[1, 6, 7, 7, 8],
       [4, 5, 8, 9, 9],
       [0, 0, 3, 3, 5]])

In [189]:
# np.argsort()

In [190]:
np.argsort(random_array)   # Sorting index

array([[4, 0, 1, 2, 3],
       [4, 0, 2, 1, 3],
       [1, 4, 0, 2, 3]], dtype=int64)

In [195]:
np.argmin(random_array,axis=1)

array([4, 4, 1], dtype=int64)

In [194]:
np.argmax(random_array,axis=1)

array([3, 1, 3], dtype=int64)

In [196]:
np.argmax(random_array, axis=0)

array([0, 1, 1, 1, 1], dtype=int64)

In [197]:
random_array

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]])

## Turn an Image into numpy array

![title](aline_red.jpg)

In [208]:
from matplotlib.image import imread

In [209]:
girl=imread("aline_red.jpg")

In [210]:
print(type(girl))

<class 'numpy.ndarray'>


In [212]:
girl.size, girl.shape, girl.ndim

(49994688, (4913, 3392, 3), 3)